### ISSUE TITLE
Default Template Causes Longer Lists to Become Incoherent

### ISSUE THREAD

**Issue by mutewinter** [bramses/chatgpt-md#58]
I used the default front matter template provided [in the repo](https://github.com/bramses/chatgpt-md/blob/master/main.ts#L40), modified for GPT-4:

```yaml
temperature: 0.9
top_p: 1
max_tokens: 512
presence_penalty: 1
frequency_penalty: 1
stream: true
stop: null
n: 1
model: gpt-4
```

I ran into issues with output of list-style responses like so:

<img width="687" alt="Screenshot 2023-04-07 at 11 49 46 AM" src="https://user-images.githubusercontent.com/305901/230649079-bfd1cb56-a6bc-448a-89eb-348878678392.png">

Near the end of the list, the formatting and text starts to become incoherent.

---

After a bit of testing, I discovered that `frequency_penalty: 1` was not the [default for the API](https://platform.openai.com/docs/api-reference/chat/create), which is `0`. Upon setting `frequency_penalty` to `0`, lists became cleaner (and more closely match the output from ChatGPT).

I was able to reproduce this same issue with the GPT 3.5 Turbo model.

## Possible Fixes

- Include a default with lower or zero penalties.
- Include many template options with pros and cons listed.

**Comment by mutewinter** [comment]
I have since updated my GPT-4 template to be more concise and as close to the OpenAPI defaults as possible:

```yaml
model: gpt-4
max_tokens: 1024
temperature: 1
presence_penalty: 0
frequency_penalty: 0
top_p: 1
n: 1
```
